set(_CATKIN_CURRENT_PACKAGE "tune_walk")
set(tune_walk_VERSION "0.1.0")
set(tune_walk_MAINTAINER "robit <robit@gmail.com>")
set(tune_walk_PACKAGE_FORMAT "1")
set(tune_walk_BUILD_DEPENDS "qt_build" "roscpp" "libqt4-dev")
set(tune_walk_BUILD_EXPORT_DEPENDS "qt_build" "roscpp" "libqt4-dev")
set(tune_walk_BUILDTOOL_DEPENDS "catkin")
set(tune_walk_BUILDTOOL_EXPORT_DEPENDS )
set(tune_walk_EXEC_DEPENDS "qt_build" "roscpp" "libqt4-dev")
set(tune_walk_RUN_DEPENDS "qt_build" "roscpp" "libqt4-dev")
set(tune_walk_TEST_DEPENDS )
set(tune_walk_DOC_DEPENDS )
set(tune_walk_URL_WEBSITE "")
set(tune_walk_URL_BUGTRACKER "")
set(tune_walk_URL_REPOSITORY "")
set(tune_walk_DEPRECATED "")