# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from msg_generate/basketball_vision23.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class basketball_vision23(genpy.Message):
  _md5sum = "e6ef028504654d91012c2d8d50a3e391"
  _type = "msg_generate/basketball_vision23"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int64 goal_cam_X
int64 goal_cam_Y
float64 goal_2d_X
float64 goal_2d_Y
float64 goal_local_X
float64 goal_local_Y
float64 goal_D
float64 robot_local_X
float64 robot_local_Y
float64 PAN
float64 TILT
int64 Scan_mode
"""
  __slots__ = ['goal_cam_X','goal_cam_Y','goal_2d_X','goal_2d_Y','goal_local_X','goal_local_Y','goal_D','robot_local_X','robot_local_Y','PAN','TILT','Scan_mode']
  _slot_types = ['int64','int64','float64','float64','float64','float64','float64','float64','float64','float64','float64','int64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       goal_cam_X,goal_cam_Y,goal_2d_X,goal_2d_Y,goal_local_X,goal_local_Y,goal_D,robot_local_X,robot_local_Y,PAN,TILT,Scan_mode

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(basketball_vision23, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.goal_cam_X is None:
        self.goal_cam_X = 0
      if self.goal_cam_Y is None:
        self.goal_cam_Y = 0
      if self.goal_2d_X is None:
        self.goal_2d_X = 0.
      if self.goal_2d_Y is None:
        self.goal_2d_Y = 0.
      if self.goal_local_X is None:
        self.goal_local_X = 0.
      if self.goal_local_Y is None:
        self.goal_local_Y = 0.
      if self.goal_D is None:
        self.goal_D = 0.
      if self.robot_local_X is None:
        self.robot_local_X = 0.
      if self.robot_local_Y is None:
        self.robot_local_Y = 0.
      if self.PAN is None:
        self.PAN = 0.
      if self.TILT is None:
        self.TILT = 0.
      if self.Scan_mode is None:
        self.Scan_mode = 0
    else:
      self.goal_cam_X = 0
      self.goal_cam_Y = 0
      self.goal_2d_X = 0.
      self.goal_2d_Y = 0.
      self.goal_local_X = 0.
      self.goal_local_Y = 0.
      self.goal_D = 0.
      self.robot_local_X = 0.
      self.robot_local_Y = 0.
      self.PAN = 0.
      self.TILT = 0.
      self.Scan_mode = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2q9dq().pack(_x.goal_cam_X, _x.goal_cam_Y, _x.goal_2d_X, _x.goal_2d_Y, _x.goal_local_X, _x.goal_local_Y, _x.goal_D, _x.robot_local_X, _x.robot_local_Y, _x.PAN, _x.TILT, _x.Scan_mode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 96
      (_x.goal_cam_X, _x.goal_cam_Y, _x.goal_2d_X, _x.goal_2d_Y, _x.goal_local_X, _x.goal_local_Y, _x.goal_D, _x.robot_local_X, _x.robot_local_Y, _x.PAN, _x.TILT, _x.Scan_mode,) = _get_struct_2q9dq().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2q9dq().pack(_x.goal_cam_X, _x.goal_cam_Y, _x.goal_2d_X, _x.goal_2d_Y, _x.goal_local_X, _x.goal_local_Y, _x.goal_D, _x.robot_local_X, _x.robot_local_Y, _x.PAN, _x.TILT, _x.Scan_mode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 96
      (_x.goal_cam_X, _x.goal_cam_Y, _x.goal_2d_X, _x.goal_2d_Y, _x.goal_local_X, _x.goal_local_Y, _x.goal_D, _x.robot_local_X, _x.robot_local_Y, _x.PAN, _x.TILT, _x.Scan_mode,) = _get_struct_2q9dq().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2q9dq = None
def _get_struct_2q9dq():
    global _struct_2q9dq
    if _struct_2q9dq is None:
        _struct_2q9dq = struct.Struct("<2q9dq")
    return _struct_2q9dq
