# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from msg_generate/HSV.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class HSV(genpy.Message):
  _md5sum = "5e59624369bde37201fa1c7dfe803e91"
  _type = "msg_generate/HSV"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 red1_dis
float64 red1_the
float64 red2_dis
float64 red2_the
float64 blue1_dis
float64 blue1_the
float64 blue2_dis
float64 blue2_the

"""
  __slots__ = ['red1_dis','red1_the','red2_dis','red2_the','blue1_dis','blue1_the','blue2_dis','blue2_the']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       red1_dis,red1_the,red2_dis,red2_the,blue1_dis,blue1_the,blue2_dis,blue2_the

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(HSV, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.red1_dis is None:
        self.red1_dis = 0.
      if self.red1_the is None:
        self.red1_the = 0.
      if self.red2_dis is None:
        self.red2_dis = 0.
      if self.red2_the is None:
        self.red2_the = 0.
      if self.blue1_dis is None:
        self.blue1_dis = 0.
      if self.blue1_the is None:
        self.blue1_the = 0.
      if self.blue2_dis is None:
        self.blue2_dis = 0.
      if self.blue2_the is None:
        self.blue2_the = 0.
    else:
      self.red1_dis = 0.
      self.red1_the = 0.
      self.red2_dis = 0.
      self.red2_the = 0.
      self.blue1_dis = 0.
      self.blue1_the = 0.
      self.blue2_dis = 0.
      self.blue2_the = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_8d().pack(_x.red1_dis, _x.red1_the, _x.red2_dis, _x.red2_the, _x.blue1_dis, _x.blue1_the, _x.blue2_dis, _x.blue2_the))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 64
      (_x.red1_dis, _x.red1_the, _x.red2_dis, _x.red2_the, _x.blue1_dis, _x.blue1_the, _x.blue2_dis, _x.blue2_the,) = _get_struct_8d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_8d().pack(_x.red1_dis, _x.red1_the, _x.red2_dis, _x.red2_the, _x.blue1_dis, _x.blue1_the, _x.blue2_dis, _x.blue2_the))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 64
      (_x.red1_dis, _x.red1_the, _x.red2_dis, _x.red2_the, _x.blue1_dis, _x.blue1_the, _x.blue2_dis, _x.blue2_the,) = _get_struct_8d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8d = None
def _get_struct_8d():
    global _struct_8d
    if _struct_8d is None:
        _struct_8d = struct.Struct("<8d")
    return _struct_8d
