# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from msg_generate/master_2_robocup_vision24.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class master_2_robocup_vision24(genpy.Message):
  _md5sum = "b5fe0eb4136cf0ddbbf95ffa2d2e7754"
  _type = "msg_generate/master_2_robocup_vision24"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int64 Scan_Mode
float64 PAN
float64 TILT
"""
  __slots__ = ['Scan_Mode','PAN','TILT']
  _slot_types = ['int64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       Scan_Mode,PAN,TILT

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(master_2_robocup_vision24, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.Scan_Mode is None:
        self.Scan_Mode = 0
      if self.PAN is None:
        self.PAN = 0.
      if self.TILT is None:
        self.TILT = 0.
    else:
      self.Scan_Mode = 0
      self.PAN = 0.
      self.TILT = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_q2d().pack(_x.Scan_Mode, _x.PAN, _x.TILT))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.Scan_Mode, _x.PAN, _x.TILT,) = _get_struct_q2d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_q2d().pack(_x.Scan_Mode, _x.PAN, _x.TILT))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.Scan_Mode, _x.PAN, _x.TILT,) = _get_struct_q2d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_q2d = None
def _get_struct_q2d():
    global _struct_q2d
    if _struct_q2d is None:
        _struct_q2d = struct.Struct("<q2d")
    return _struct_q2d
