# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from msg_generate/robocup_vision23_feature.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class robocup_vision23_feature(genpy.Message):
  _md5sum = "90f95fdb2af41305af35e1195995ece4"
  _type = "msg_generate/robocup_vision23_feature"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64[] CONFIDENCE
float64[] DISTANCE
float64[] POINT_VEC_X
float64[] POINT_VEC_Y
float64[] TYPE
"""
  __slots__ = ['CONFIDENCE','DISTANCE','POINT_VEC_X','POINT_VEC_Y','TYPE']
  _slot_types = ['float64[]','float64[]','float64[]','float64[]','float64[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       CONFIDENCE,DISTANCE,POINT_VEC_X,POINT_VEC_Y,TYPE

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(robocup_vision23_feature, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.CONFIDENCE is None:
        self.CONFIDENCE = []
      if self.DISTANCE is None:
        self.DISTANCE = []
      if self.POINT_VEC_X is None:
        self.POINT_VEC_X = []
      if self.POINT_VEC_Y is None:
        self.POINT_VEC_Y = []
      if self.TYPE is None:
        self.TYPE = []
    else:
      self.CONFIDENCE = []
      self.DISTANCE = []
      self.POINT_VEC_X = []
      self.POINT_VEC_Y = []
      self.TYPE = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.CONFIDENCE)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.CONFIDENCE))
      length = len(self.DISTANCE)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.DISTANCE))
      length = len(self.POINT_VEC_X)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.POINT_VEC_X))
      length = len(self.POINT_VEC_Y)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.POINT_VEC_Y))
      length = len(self.TYPE)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.TYPE))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.CONFIDENCE = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.DISTANCE = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.POINT_VEC_X = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.POINT_VEC_Y = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.TYPE = s.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.CONFIDENCE)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.CONFIDENCE.tostring())
      length = len(self.DISTANCE)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.DISTANCE.tostring())
      length = len(self.POINT_VEC_X)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.POINT_VEC_X.tostring())
      length = len(self.POINT_VEC_Y)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.POINT_VEC_Y.tostring())
      length = len(self.TYPE)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.TYPE.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.CONFIDENCE = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.DISTANCE = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.POINT_VEC_X = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.POINT_VEC_Y = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.TYPE = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
