# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from msg_generate/Running_2020_vision.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Running_2020_vision(genpy.Message):
  _md5sum = "4006f37f440c035b6febc61d2cd4ff1a"
  _type = "msg_generate/Running_2020_vision"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int64 Way
int64 start_x
int64 start_y
int64 goal_x
int64 goal_y
int64 direction
bool recog_goal_x
"""
  __slots__ = ['Way','start_x','start_y','goal_x','goal_y','direction','recog_goal_x']
  _slot_types = ['int64','int64','int64','int64','int64','int64','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       Way,start_x,start_y,goal_x,goal_y,direction,recog_goal_x

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Running_2020_vision, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.Way is None:
        self.Way = 0
      if self.start_x is None:
        self.start_x = 0
      if self.start_y is None:
        self.start_y = 0
      if self.goal_x is None:
        self.goal_x = 0
      if self.goal_y is None:
        self.goal_y = 0
      if self.direction is None:
        self.direction = 0
      if self.recog_goal_x is None:
        self.recog_goal_x = False
    else:
      self.Way = 0
      self.start_x = 0
      self.start_y = 0
      self.goal_x = 0
      self.goal_y = 0
      self.direction = 0
      self.recog_goal_x = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6qB().pack(_x.Way, _x.start_x, _x.start_y, _x.goal_x, _x.goal_y, _x.direction, _x.recog_goal_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 49
      (_x.Way, _x.start_x, _x.start_y, _x.goal_x, _x.goal_y, _x.direction, _x.recog_goal_x,) = _get_struct_6qB().unpack(str[start:end])
      self.recog_goal_x = bool(self.recog_goal_x)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6qB().pack(_x.Way, _x.start_x, _x.start_y, _x.goal_x, _x.goal_y, _x.direction, _x.recog_goal_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 49
      (_x.Way, _x.start_x, _x.start_y, _x.goal_x, _x.goal_y, _x.direction, _x.recog_goal_x,) = _get_struct_6qB().unpack(str[start:end])
      self.recog_goal_x = bool(self.recog_goal_x)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6qB = None
def _get_struct_6qB():
    global _struct_6qB
    if _struct_6qB is None:
        _struct_6qB = struct.Struct("<6qB")
    return _struct_6qB
