# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from msg_generate/udp_msg_TC_Kicker.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class udp_msg_TC_Kicker(genpy.Message):
  _md5sum = "4f5ba7b091b51220f871e749e172c551"
  _type = "msg_generate/udp_msg_TC_Kicker"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int64 robot_num
int64 robot_case

int64 local_x
int64 local_y 
int64 local_yaw




"""
  __slots__ = ['robot_num','robot_case','local_x','local_y','local_yaw']
  _slot_types = ['int64','int64','int64','int64','int64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       robot_num,robot_case,local_x,local_y,local_yaw

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(udp_msg_TC_Kicker, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.robot_num is None:
        self.robot_num = 0
      if self.robot_case is None:
        self.robot_case = 0
      if self.local_x is None:
        self.local_x = 0
      if self.local_y is None:
        self.local_y = 0
      if self.local_yaw is None:
        self.local_yaw = 0
    else:
      self.robot_num = 0
      self.robot_case = 0
      self.local_x = 0
      self.local_y = 0
      self.local_yaw = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_5q().pack(_x.robot_num, _x.robot_case, _x.local_x, _x.local_y, _x.local_yaw))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.robot_num, _x.robot_case, _x.local_x, _x.local_y, _x.local_yaw,) = _get_struct_5q().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_5q().pack(_x.robot_num, _x.robot_case, _x.local_x, _x.local_y, _x.local_yaw))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.robot_num, _x.robot_case, _x.local_x, _x.local_y, _x.local_yaw,) = _get_struct_5q().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5q = None
def _get_struct_5q():
    global _struct_5q
    if _struct_5q is None:
        _struct_5q = struct.Struct("<5q")
    return _struct_5q
