// Generated by gencpp from file msg_generate/master2hanoi_vision2019msg.msg
// DO NOT EDIT!


#ifndef MSG_GENERATE_MESSAGE_MASTER2HANOI_VISION2019MSG_H
#define MSG_GENERATE_MESSAGE_MASTER2HANOI_VISION2019MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg_generate
{
template <class ContainerAllocator>
struct master2hanoi_vision2019msg_
{
  typedef master2hanoi_vision2019msg_<ContainerAllocator> Type;

  master2hanoi_vision2019msg_()
    : color_what(0)
    , alpha_check(false)  {
    }
  master2hanoi_vision2019msg_(const ContainerAllocator& _alloc)
    : color_what(0)
    , alpha_check(false)  {
  (void)_alloc;
    }



   typedef int32_t _color_what_type;
  _color_what_type color_what;

   typedef uint8_t _alpha_check_type;
  _alpha_check_type alpha_check;





  typedef boost::shared_ptr< ::msg_generate::master2hanoi_vision2019msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_generate::master2hanoi_vision2019msg_<ContainerAllocator> const> ConstPtr;

}; // struct master2hanoi_vision2019msg_

typedef ::msg_generate::master2hanoi_vision2019msg_<std::allocator<void> > master2hanoi_vision2019msg;

typedef boost::shared_ptr< ::msg_generate::master2hanoi_vision2019msg > master2hanoi_vision2019msgPtr;
typedef boost::shared_ptr< ::msg_generate::master2hanoi_vision2019msg const> master2hanoi_vision2019msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_generate::master2hanoi_vision2019msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_generate::master2hanoi_vision2019msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_generate::master2hanoi_vision2019msg_<ContainerAllocator1> & lhs, const ::msg_generate::master2hanoi_vision2019msg_<ContainerAllocator2> & rhs)
{
  return lhs.color_what == rhs.color_what &&
    lhs.alpha_check == rhs.alpha_check;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_generate::master2hanoi_vision2019msg_<ContainerAllocator1> & lhs, const ::msg_generate::master2hanoi_vision2019msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_generate

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_generate::master2hanoi_vision2019msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_generate::master2hanoi_vision2019msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_generate::master2hanoi_vision2019msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_generate::master2hanoi_vision2019msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_generate::master2hanoi_vision2019msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_generate::master2hanoi_vision2019msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_generate::master2hanoi_vision2019msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0da4621181e0545911e6b295c023e0d4";
  }

  static const char* value(const ::msg_generate::master2hanoi_vision2019msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0da4621181e05459ULL;
  static const uint64_t static_value2 = 0x11e6b295c023e0d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_generate::master2hanoi_vision2019msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_generate/master2hanoi_vision2019msg";
  }

  static const char* value(const ::msg_generate::master2hanoi_vision2019msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_generate::master2hanoi_vision2019msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 color_what\n"
"bool alpha_check\n"
;
  }

  static const char* value(const ::msg_generate::master2hanoi_vision2019msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_generate::master2hanoi_vision2019msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.color_what);
      stream.next(m.alpha_check);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct master2hanoi_vision2019msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_generate::master2hanoi_vision2019msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_generate::master2hanoi_vision2019msg_<ContainerAllocator>& v)
  {
    s << indent << "color_what: ";
    Printer<int32_t>::stream(s, indent + "  ", v.color_what);
    s << indent << "alpha_check: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.alpha_check);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_GENERATE_MESSAGE_MASTER2HANOI_VISION2019MSG_H
