// Generated by gencpp from file msg_generate/master2vision_msg.msg
// DO NOT EDIT!


#ifndef MSG_GENERATE_MESSAGE_MASTER2VISION_MSG_H
#define MSG_GENERATE_MESSAGE_MASTER2VISION_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg_generate
{
template <class ContainerAllocator>
struct master2vision_msg_
{
  typedef master2vision_msg_<ContainerAllocator> Type;

  master2vision_msg_()
    : TILT(0.0)
    , PAN(0.0)  {
    }
  master2vision_msg_(const ContainerAllocator& _alloc)
    : TILT(0.0)
    , PAN(0.0)  {
  (void)_alloc;
    }



   typedef double _TILT_type;
  _TILT_type TILT;

   typedef double _PAN_type;
  _PAN_type PAN;





  typedef boost::shared_ptr< ::msg_generate::master2vision_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_generate::master2vision_msg_<ContainerAllocator> const> ConstPtr;

}; // struct master2vision_msg_

typedef ::msg_generate::master2vision_msg_<std::allocator<void> > master2vision_msg;

typedef boost::shared_ptr< ::msg_generate::master2vision_msg > master2vision_msgPtr;
typedef boost::shared_ptr< ::msg_generate::master2vision_msg const> master2vision_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_generate::master2vision_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_generate::master2vision_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_generate::master2vision_msg_<ContainerAllocator1> & lhs, const ::msg_generate::master2vision_msg_<ContainerAllocator2> & rhs)
{
  return lhs.TILT == rhs.TILT &&
    lhs.PAN == rhs.PAN;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_generate::master2vision_msg_<ContainerAllocator1> & lhs, const ::msg_generate::master2vision_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_generate

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_generate::master2vision_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_generate::master2vision_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_generate::master2vision_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_generate::master2vision_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_generate::master2vision_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_generate::master2vision_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_generate::master2vision_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8e3fffe76719ba65b10a2f461e54333b";
  }

  static const char* value(const ::msg_generate::master2vision_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8e3fffe76719ba65ULL;
  static const uint64_t static_value2 = 0xb10a2f461e54333bULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_generate::master2vision_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_generate/master2vision_msg";
  }

  static const char* value(const ::msg_generate::master2vision_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_generate::master2vision_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 TILT\n"
"float64 PAN\n"
;
  }

  static const char* value(const ::msg_generate::master2vision_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_generate::master2vision_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.TILT);
      stream.next(m.PAN);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct master2vision_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_generate::master2vision_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_generate::master2vision_msg_<ContainerAllocator>& v)
  {
    s << indent << "TILT: ";
    Printer<double>::stream(s, indent + "  ", v.TILT);
    s << indent << "PAN: ";
    Printer<double>::stream(s, indent + "  ", v.PAN);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_GENERATE_MESSAGE_MASTER2VISION_MSG_H
