// Generated by gencpp from file msg_generate/pan_tilt_msg.msg
// DO NOT EDIT!


#ifndef MSG_GENERATE_MESSAGE_PAN_TILT_MSG_H
#define MSG_GENERATE_MESSAGE_PAN_TILT_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg_generate
{
template <class ContainerAllocator>
struct pan_tilt_msg_
{
  typedef pan_tilt_msg_<ContainerAllocator> Type;

  pan_tilt_msg_()
    : waist_flag(0)
    , Angle_Yaw(0.0)
    , Angle_Pitch(0.0)  {
    }
  pan_tilt_msg_(const ContainerAllocator& _alloc)
    : waist_flag(0)
    , Angle_Yaw(0.0)
    , Angle_Pitch(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _waist_flag_type;
  _waist_flag_type waist_flag;

   typedef double _Angle_Yaw_type;
  _Angle_Yaw_type Angle_Yaw;

   typedef double _Angle_Pitch_type;
  _Angle_Pitch_type Angle_Pitch;





  typedef boost::shared_ptr< ::msg_generate::pan_tilt_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_generate::pan_tilt_msg_<ContainerAllocator> const> ConstPtr;

}; // struct pan_tilt_msg_

typedef ::msg_generate::pan_tilt_msg_<std::allocator<void> > pan_tilt_msg;

typedef boost::shared_ptr< ::msg_generate::pan_tilt_msg > pan_tilt_msgPtr;
typedef boost::shared_ptr< ::msg_generate::pan_tilt_msg const> pan_tilt_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_generate::pan_tilt_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_generate::pan_tilt_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_generate::pan_tilt_msg_<ContainerAllocator1> & lhs, const ::msg_generate::pan_tilt_msg_<ContainerAllocator2> & rhs)
{
  return lhs.waist_flag == rhs.waist_flag &&
    lhs.Angle_Yaw == rhs.Angle_Yaw &&
    lhs.Angle_Pitch == rhs.Angle_Pitch;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_generate::pan_tilt_msg_<ContainerAllocator1> & lhs, const ::msg_generate::pan_tilt_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_generate

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_generate::pan_tilt_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_generate::pan_tilt_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_generate::pan_tilt_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_generate::pan_tilt_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_generate::pan_tilt_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_generate::pan_tilt_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_generate::pan_tilt_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "611b91cd650b11bf3bb556113e5f1029";
  }

  static const char* value(const ::msg_generate::pan_tilt_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x611b91cd650b11bfULL;
  static const uint64_t static_value2 = 0x3bb556113e5f1029ULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_generate::pan_tilt_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_generate/pan_tilt_msg";
  }

  static const char* value(const ::msg_generate::pan_tilt_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_generate::pan_tilt_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 waist_flag\n"
"\n"
"float64 Angle_Yaw\n"
"float64 Angle_Pitch\n"
;
  }

  static const char* value(const ::msg_generate::pan_tilt_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_generate::pan_tilt_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.waist_flag);
      stream.next(m.Angle_Yaw);
      stream.next(m.Angle_Pitch);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pan_tilt_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_generate::pan_tilt_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_generate::pan_tilt_msg_<ContainerAllocator>& v)
  {
    s << indent << "waist_flag: ";
    Printer<int32_t>::stream(s, indent + "  ", v.waist_flag);
    s << indent << "Angle_Yaw: ";
    Printer<double>::stream(s, indent + "  ", v.Angle_Yaw);
    s << indent << "Angle_Pitch: ";
    Printer<double>::stream(s, indent + "  ", v.Angle_Pitch);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_GENERATE_MESSAGE_PAN_TILT_MSG_H
