// Generated by gencpp from file msg_generate/running_vision23.msg
// DO NOT EDIT!


#ifndef MSG_GENERATE_MESSAGE_RUNNING_VISION23_H
#define MSG_GENERATE_MESSAGE_RUNNING_VISION23_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg_generate
{
template <class ContainerAllocator>
struct running_vision23_
{
  typedef running_vision23_<ContainerAllocator> Type;

  running_vision23_()
    : line_cam_X()
    , line_cam_Y()
    , line_2d_X()
    , line_2d_Y()
    , line_D()
    , line_theta(0.0)
    , cross_cam_X(0)
    , cross_cam_Y(0)
    , cross_2d_X(0.0)
    , cross_2d_Y(0.0)
    , cross_D(0.0)
    , hurdle_cam_X(0)
    , hurdle_cam_Y(0)
    , hurdle_2d_X(0.0)
    , hurdle_2d_Y(0.0)
    , hurdle_D(0.0)
    , hurdle_theta(0.0)
    , PAN(0.0)
    , TILT(0.0)
    , Scan_mode(0)  {
    }
  running_vision23_(const ContainerAllocator& _alloc)
    : line_cam_X(_alloc)
    , line_cam_Y(_alloc)
    , line_2d_X(_alloc)
    , line_2d_Y(_alloc)
    , line_D(_alloc)
    , line_theta(0.0)
    , cross_cam_X(0)
    , cross_cam_Y(0)
    , cross_2d_X(0.0)
    , cross_2d_Y(0.0)
    , cross_D(0.0)
    , hurdle_cam_X(0)
    , hurdle_cam_Y(0)
    , hurdle_2d_X(0.0)
    , hurdle_2d_Y(0.0)
    , hurdle_D(0.0)
    , hurdle_theta(0.0)
    , PAN(0.0)
    , TILT(0.0)
    , Scan_mode(0)  {
  (void)_alloc;
    }



   typedef std::vector<int64_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int64_t>> _line_cam_X_type;
  _line_cam_X_type line_cam_X;

   typedef std::vector<int64_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int64_t>> _line_cam_Y_type;
  _line_cam_Y_type line_cam_Y;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _line_2d_X_type;
  _line_2d_X_type line_2d_X;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _line_2d_Y_type;
  _line_2d_Y_type line_2d_Y;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _line_D_type;
  _line_D_type line_D;

   typedef double _line_theta_type;
  _line_theta_type line_theta;

   typedef int64_t _cross_cam_X_type;
  _cross_cam_X_type cross_cam_X;

   typedef int64_t _cross_cam_Y_type;
  _cross_cam_Y_type cross_cam_Y;

   typedef double _cross_2d_X_type;
  _cross_2d_X_type cross_2d_X;

   typedef double _cross_2d_Y_type;
  _cross_2d_Y_type cross_2d_Y;

   typedef double _cross_D_type;
  _cross_D_type cross_D;

   typedef int64_t _hurdle_cam_X_type;
  _hurdle_cam_X_type hurdle_cam_X;

   typedef int64_t _hurdle_cam_Y_type;
  _hurdle_cam_Y_type hurdle_cam_Y;

   typedef double _hurdle_2d_X_type;
  _hurdle_2d_X_type hurdle_2d_X;

   typedef double _hurdle_2d_Y_type;
  _hurdle_2d_Y_type hurdle_2d_Y;

   typedef double _hurdle_D_type;
  _hurdle_D_type hurdle_D;

   typedef double _hurdle_theta_type;
  _hurdle_theta_type hurdle_theta;

   typedef double _PAN_type;
  _PAN_type PAN;

   typedef double _TILT_type;
  _TILT_type TILT;

   typedef int64_t _Scan_mode_type;
  _Scan_mode_type Scan_mode;





  typedef boost::shared_ptr< ::msg_generate::running_vision23_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_generate::running_vision23_<ContainerAllocator> const> ConstPtr;

}; // struct running_vision23_

typedef ::msg_generate::running_vision23_<std::allocator<void> > running_vision23;

typedef boost::shared_ptr< ::msg_generate::running_vision23 > running_vision23Ptr;
typedef boost::shared_ptr< ::msg_generate::running_vision23 const> running_vision23ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_generate::running_vision23_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_generate::running_vision23_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_generate::running_vision23_<ContainerAllocator1> & lhs, const ::msg_generate::running_vision23_<ContainerAllocator2> & rhs)
{
  return lhs.line_cam_X == rhs.line_cam_X &&
    lhs.line_cam_Y == rhs.line_cam_Y &&
    lhs.line_2d_X == rhs.line_2d_X &&
    lhs.line_2d_Y == rhs.line_2d_Y &&
    lhs.line_D == rhs.line_D &&
    lhs.line_theta == rhs.line_theta &&
    lhs.cross_cam_X == rhs.cross_cam_X &&
    lhs.cross_cam_Y == rhs.cross_cam_Y &&
    lhs.cross_2d_X == rhs.cross_2d_X &&
    lhs.cross_2d_Y == rhs.cross_2d_Y &&
    lhs.cross_D == rhs.cross_D &&
    lhs.hurdle_cam_X == rhs.hurdle_cam_X &&
    lhs.hurdle_cam_Y == rhs.hurdle_cam_Y &&
    lhs.hurdle_2d_X == rhs.hurdle_2d_X &&
    lhs.hurdle_2d_Y == rhs.hurdle_2d_Y &&
    lhs.hurdle_D == rhs.hurdle_D &&
    lhs.hurdle_theta == rhs.hurdle_theta &&
    lhs.PAN == rhs.PAN &&
    lhs.TILT == rhs.TILT &&
    lhs.Scan_mode == rhs.Scan_mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_generate::running_vision23_<ContainerAllocator1> & lhs, const ::msg_generate::running_vision23_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_generate

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_generate::running_vision23_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_generate::running_vision23_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_generate::running_vision23_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_generate::running_vision23_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_generate::running_vision23_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_generate::running_vision23_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_generate::running_vision23_<ContainerAllocator> >
{
  static const char* value()
  {
    return "84bbd3957c09a95986b5eb7beba9cf54";
  }

  static const char* value(const ::msg_generate::running_vision23_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x84bbd3957c09a959ULL;
  static const uint64_t static_value2 = 0x86b5eb7beba9cf54ULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_generate::running_vision23_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_generate/running_vision23";
  }

  static const char* value(const ::msg_generate::running_vision23_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_generate::running_vision23_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64[] line_cam_X\n"
"int64[] line_cam_Y\n"
"float64[] line_2d_X\n"
"float64[] line_2d_Y\n"
"float64[] line_D\n"
"float64 line_theta\n"
"\n"
"int64 cross_cam_X\n"
"int64 cross_cam_Y\n"
"float64 cross_2d_X\n"
"float64 cross_2d_Y\n"
"float64 cross_D\n"
"\n"
"int64 hurdle_cam_X\n"
"int64 hurdle_cam_Y\n"
"float64 hurdle_2d_X\n"
"float64 hurdle_2d_Y\n"
"float64 hurdle_D\n"
"float64 hurdle_theta\n"
"\n"
"float64 PAN\n"
"float64 TILT\n"
"int64 Scan_mode\n"
"\n"
"\n"
;
  }

  static const char* value(const ::msg_generate::running_vision23_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_generate::running_vision23_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.line_cam_X);
      stream.next(m.line_cam_Y);
      stream.next(m.line_2d_X);
      stream.next(m.line_2d_Y);
      stream.next(m.line_D);
      stream.next(m.line_theta);
      stream.next(m.cross_cam_X);
      stream.next(m.cross_cam_Y);
      stream.next(m.cross_2d_X);
      stream.next(m.cross_2d_Y);
      stream.next(m.cross_D);
      stream.next(m.hurdle_cam_X);
      stream.next(m.hurdle_cam_Y);
      stream.next(m.hurdle_2d_X);
      stream.next(m.hurdle_2d_Y);
      stream.next(m.hurdle_D);
      stream.next(m.hurdle_theta);
      stream.next(m.PAN);
      stream.next(m.TILT);
      stream.next(m.Scan_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct running_vision23_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_generate::running_vision23_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_generate::running_vision23_<ContainerAllocator>& v)
  {
    s << indent << "line_cam_X[]" << std::endl;
    for (size_t i = 0; i < v.line_cam_X.size(); ++i)
    {
      s << indent << "  line_cam_X[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.line_cam_X[i]);
    }
    s << indent << "line_cam_Y[]" << std::endl;
    for (size_t i = 0; i < v.line_cam_Y.size(); ++i)
    {
      s << indent << "  line_cam_Y[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.line_cam_Y[i]);
    }
    s << indent << "line_2d_X[]" << std::endl;
    for (size_t i = 0; i < v.line_2d_X.size(); ++i)
    {
      s << indent << "  line_2d_X[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.line_2d_X[i]);
    }
    s << indent << "line_2d_Y[]" << std::endl;
    for (size_t i = 0; i < v.line_2d_Y.size(); ++i)
    {
      s << indent << "  line_2d_Y[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.line_2d_Y[i]);
    }
    s << indent << "line_D[]" << std::endl;
    for (size_t i = 0; i < v.line_D.size(); ++i)
    {
      s << indent << "  line_D[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.line_D[i]);
    }
    s << indent << "line_theta: ";
    Printer<double>::stream(s, indent + "  ", v.line_theta);
    s << indent << "cross_cam_X: ";
    Printer<int64_t>::stream(s, indent + "  ", v.cross_cam_X);
    s << indent << "cross_cam_Y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.cross_cam_Y);
    s << indent << "cross_2d_X: ";
    Printer<double>::stream(s, indent + "  ", v.cross_2d_X);
    s << indent << "cross_2d_Y: ";
    Printer<double>::stream(s, indent + "  ", v.cross_2d_Y);
    s << indent << "cross_D: ";
    Printer<double>::stream(s, indent + "  ", v.cross_D);
    s << indent << "hurdle_cam_X: ";
    Printer<int64_t>::stream(s, indent + "  ", v.hurdle_cam_X);
    s << indent << "hurdle_cam_Y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.hurdle_cam_Y);
    s << indent << "hurdle_2d_X: ";
    Printer<double>::stream(s, indent + "  ", v.hurdle_2d_X);
    s << indent << "hurdle_2d_Y: ";
    Printer<double>::stream(s, indent + "  ", v.hurdle_2d_Y);
    s << indent << "hurdle_D: ";
    Printer<double>::stream(s, indent + "  ", v.hurdle_D);
    s << indent << "hurdle_theta: ";
    Printer<double>::stream(s, indent + "  ", v.hurdle_theta);
    s << indent << "PAN: ";
    Printer<double>::stream(s, indent + "  ", v.PAN);
    s << indent << "TILT: ";
    Printer<double>::stream(s, indent + "  ", v.TILT);
    s << indent << "Scan_mode: ";
    Printer<int64_t>::stream(s, indent + "  ", v.Scan_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_GENERATE_MESSAGE_RUNNING_VISION23_H
