// Generated by gencpp from file msg_generate/udp_msg_TC_Helper.msg
// DO NOT EDIT!


#ifndef MSG_GENERATE_MESSAGE_UDP_MSG_TC_HELPER_H
#define MSG_GENERATE_MESSAGE_UDP_MSG_TC_HELPER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg_generate
{
template <class ContainerAllocator>
struct udp_msg_TC_Helper_
{
  typedef udp_msg_TC_Helper_<ContainerAllocator> Type;

  udp_msg_TC_Helper_()
    : robot_num(0)
    , robot_case(0)
    , robot_x_order(0)
    , robot_y_order(0)
    , robot_ik_x_order(0)
    , robot_ik_y_order(0)
    , robot_ik_yaw_order(0)
    , ball_x(0)
    , ball_y(0)
    , ballDist(0)
    , ballTheta(0)  {
    }
  udp_msg_TC_Helper_(const ContainerAllocator& _alloc)
    : robot_num(0)
    , robot_case(0)
    , robot_x_order(0)
    , robot_y_order(0)
    , robot_ik_x_order(0)
    , robot_ik_y_order(0)
    , robot_ik_yaw_order(0)
    , ball_x(0)
    , ball_y(0)
    , ballDist(0)
    , ballTheta(0)  {
  (void)_alloc;
    }



   typedef int64_t _robot_num_type;
  _robot_num_type robot_num;

   typedef int64_t _robot_case_type;
  _robot_case_type robot_case;

   typedef int64_t _robot_x_order_type;
  _robot_x_order_type robot_x_order;

   typedef int64_t _robot_y_order_type;
  _robot_y_order_type robot_y_order;

   typedef int64_t _robot_ik_x_order_type;
  _robot_ik_x_order_type robot_ik_x_order;

   typedef int64_t _robot_ik_y_order_type;
  _robot_ik_y_order_type robot_ik_y_order;

   typedef int64_t _robot_ik_yaw_order_type;
  _robot_ik_yaw_order_type robot_ik_yaw_order;

   typedef int64_t _ball_x_type;
  _ball_x_type ball_x;

   typedef int64_t _ball_y_type;
  _ball_y_type ball_y;

   typedef int64_t _ballDist_type;
  _ballDist_type ballDist;

   typedef int64_t _ballTheta_type;
  _ballTheta_type ballTheta;





  typedef boost::shared_ptr< ::msg_generate::udp_msg_TC_Helper_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_generate::udp_msg_TC_Helper_<ContainerAllocator> const> ConstPtr;

}; // struct udp_msg_TC_Helper_

typedef ::msg_generate::udp_msg_TC_Helper_<std::allocator<void> > udp_msg_TC_Helper;

typedef boost::shared_ptr< ::msg_generate::udp_msg_TC_Helper > udp_msg_TC_HelperPtr;
typedef boost::shared_ptr< ::msg_generate::udp_msg_TC_Helper const> udp_msg_TC_HelperConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_generate::udp_msg_TC_Helper_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_generate::udp_msg_TC_Helper_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_generate::udp_msg_TC_Helper_<ContainerAllocator1> & lhs, const ::msg_generate::udp_msg_TC_Helper_<ContainerAllocator2> & rhs)
{
  return lhs.robot_num == rhs.robot_num &&
    lhs.robot_case == rhs.robot_case &&
    lhs.robot_x_order == rhs.robot_x_order &&
    lhs.robot_y_order == rhs.robot_y_order &&
    lhs.robot_ik_x_order == rhs.robot_ik_x_order &&
    lhs.robot_ik_y_order == rhs.robot_ik_y_order &&
    lhs.robot_ik_yaw_order == rhs.robot_ik_yaw_order &&
    lhs.ball_x == rhs.ball_x &&
    lhs.ball_y == rhs.ball_y &&
    lhs.ballDist == rhs.ballDist &&
    lhs.ballTheta == rhs.ballTheta;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_generate::udp_msg_TC_Helper_<ContainerAllocator1> & lhs, const ::msg_generate::udp_msg_TC_Helper_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_generate

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_generate::udp_msg_TC_Helper_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_generate::udp_msg_TC_Helper_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_generate::udp_msg_TC_Helper_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_generate::udp_msg_TC_Helper_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_generate::udp_msg_TC_Helper_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_generate::udp_msg_TC_Helper_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_generate::udp_msg_TC_Helper_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6961c7de19af71cbd4139ee3940f46a0";
  }

  static const char* value(const ::msg_generate::udp_msg_TC_Helper_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6961c7de19af71cbULL;
  static const uint64_t static_value2 = 0xd4139ee3940f46a0ULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_generate::udp_msg_TC_Helper_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_generate/udp_msg_TC_Helper";
  }

  static const char* value(const ::msg_generate::udp_msg_TC_Helper_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_generate::udp_msg_TC_Helper_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 robot_num\n"
"int64 robot_case\n"
"\n"
"int64 robot_x_order\n"
"int64 robot_y_order \n"
"\n"
"int64 robot_ik_x_order\n"
"int64 robot_ik_y_order\n"
"int64 robot_ik_yaw_order\n"
"\n"
"int64 ball_x\n"
"int64 ball_y\n"
"int64 ballDist\n"
"int64 ballTheta\n"
"\n"
"\n"
"\n"
;
  }

  static const char* value(const ::msg_generate::udp_msg_TC_Helper_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_generate::udp_msg_TC_Helper_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_num);
      stream.next(m.robot_case);
      stream.next(m.robot_x_order);
      stream.next(m.robot_y_order);
      stream.next(m.robot_ik_x_order);
      stream.next(m.robot_ik_y_order);
      stream.next(m.robot_ik_yaw_order);
      stream.next(m.ball_x);
      stream.next(m.ball_y);
      stream.next(m.ballDist);
      stream.next(m.ballTheta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct udp_msg_TC_Helper_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_generate::udp_msg_TC_Helper_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_generate::udp_msg_TC_Helper_<ContainerAllocator>& v)
  {
    s << indent << "robot_num: ";
    Printer<int64_t>::stream(s, indent + "  ", v.robot_num);
    s << indent << "robot_case: ";
    Printer<int64_t>::stream(s, indent + "  ", v.robot_case);
    s << indent << "robot_x_order: ";
    Printer<int64_t>::stream(s, indent + "  ", v.robot_x_order);
    s << indent << "robot_y_order: ";
    Printer<int64_t>::stream(s, indent + "  ", v.robot_y_order);
    s << indent << "robot_ik_x_order: ";
    Printer<int64_t>::stream(s, indent + "  ", v.robot_ik_x_order);
    s << indent << "robot_ik_y_order: ";
    Printer<int64_t>::stream(s, indent + "  ", v.robot_ik_y_order);
    s << indent << "robot_ik_yaw_order: ";
    Printer<int64_t>::stream(s, indent + "  ", v.robot_ik_yaw_order);
    s << indent << "ball_x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.ball_x);
    s << indent << "ball_y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.ball_y);
    s << indent << "ballDist: ";
    Printer<int64_t>::stream(s, indent + "  ", v.ballDist);
    s << indent << "ballTheta: ";
    Printer<int64_t>::stream(s, indent + "  ", v.ballTheta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_GENERATE_MESSAGE_UDP_MSG_TC_HELPER_H
