// Generated by gencpp from file msg_generate/udp_msg.msg
// DO NOT EDIT!


#ifndef MSG_GENERATE_MESSAGE_UDP_MSG_H
#define MSG_GENERATE_MESSAGE_UDP_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg_generate
{
template <class ContainerAllocator>
struct udp_msg_
{
  typedef udp_msg_<ContainerAllocator> Type;

  udp_msg_()
    : field_area(0)
    , ball_area(0)
    , robocup_case(0)
    , ballDist(0.0)  {
    }
  udp_msg_(const ContainerAllocator& _alloc)
    : field_area(0)
    , ball_area(0)
    , robocup_case(0)
    , ballDist(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _field_area_type;
  _field_area_type field_area;

   typedef int32_t _ball_area_type;
  _ball_area_type ball_area;

   typedef int32_t _robocup_case_type;
  _robocup_case_type robocup_case;

   typedef double _ballDist_type;
  _ballDist_type ballDist;





  typedef boost::shared_ptr< ::msg_generate::udp_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_generate::udp_msg_<ContainerAllocator> const> ConstPtr;

}; // struct udp_msg_

typedef ::msg_generate::udp_msg_<std::allocator<void> > udp_msg;

typedef boost::shared_ptr< ::msg_generate::udp_msg > udp_msgPtr;
typedef boost::shared_ptr< ::msg_generate::udp_msg const> udp_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_generate::udp_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_generate::udp_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_generate::udp_msg_<ContainerAllocator1> & lhs, const ::msg_generate::udp_msg_<ContainerAllocator2> & rhs)
{
  return lhs.field_area == rhs.field_area &&
    lhs.ball_area == rhs.ball_area &&
    lhs.robocup_case == rhs.robocup_case &&
    lhs.ballDist == rhs.ballDist;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_generate::udp_msg_<ContainerAllocator1> & lhs, const ::msg_generate::udp_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_generate

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_generate::udp_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_generate::udp_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_generate::udp_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_generate::udp_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_generate::udp_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_generate::udp_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_generate::udp_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "705379b613a1dfa415f111dd5f542624";
  }

  static const char* value(const ::msg_generate::udp_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x705379b613a1dfa4ULL;
  static const uint64_t static_value2 = 0x15f111dd5f542624ULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_generate::udp_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_generate/udp_msg";
  }

  static const char* value(const ::msg_generate::udp_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_generate::udp_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 field_area\n"
"int32 ball_area\n"
"int32 robocup_case\n"
"float64 ballDist\n"
;
  }

  static const char* value(const ::msg_generate::udp_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_generate::udp_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.field_area);
      stream.next(m.ball_area);
      stream.next(m.robocup_case);
      stream.next(m.ballDist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct udp_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_generate::udp_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_generate::udp_msg_<ContainerAllocator>& v)
  {
    s << indent << "field_area: ";
    Printer<int32_t>::stream(s, indent + "  ", v.field_area);
    s << indent << "ball_area: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ball_area);
    s << indent << "robocup_case: ";
    Printer<int32_t>::stream(s, indent + "  ", v.robocup_case);
    s << indent << "ballDist: ";
    Printer<double>::stream(s, indent + "  ", v.ballDist);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_GENERATE_MESSAGE_UDP_MSG_H
