(cl:in-package msg_generate-msg)
(cl:export '(BALLX-VAL
          BALLX
          BALLY-VAL
          BALLY
          BALLDIST-VAL
          BALLDIST
          BALLTHETA-VAL
          BALLTHETA
          CYLINDERX-VAL
          CYLINDERX
          CYLINDERY-VAL
          CYLINDERY
          CYLINDERDIST-VAL
          CYLINDERDIST
          CYLINDERTHETA-VAL
          CYLINDERTHETA
          DIRECTX-VAL
          DIRECTX
          DIRECTY-VAL
          DIRECTY
          DIRECTDIST-VAL
          DIRECTDIST
          DIRECTTHETA-VAL
          DIRECTTHETA
          FIRST_START-VAL
          FIRST_START
          CIRCLEX-VAL
          CIRCLEX
          CIRCLEY-VAL
          CIRCLEY
))