(cl:in-package msg_generate-msg)
(cl:export '(ANG_R_0-VAL
          ANG_R_0
          ANG_R_1-VAL
          ANG_R_1
          ANG_R_2-VAL
          ANG_R_2
          ANG_R_3-VAL
          ANG_R_3
          ANG_R_4-VAL
          ANG_R_4
          ANG_R_5-VAL
          ANG_R_5
          ANG_R_6-VAL
          ANG_R_6
          ANG_R_7-VAL
          ANG_R_7
          ANG_R_8-VAL
          ANG_R_8
          ANG_L_0-VAL
          ANG_L_0
          ANG_L_1-VAL
          ANG_L_1
          ANG_L_2-VAL
          ANG_L_2
          ANG_L_3-VAL
          ANG_L_3
          ANG_L_4-VAL
          ANG_L_4
          ANG_L_5-VAL
          ANG_L_5
          ANG_L_6-VAL
          ANG_L_6
          ANG_L_7-VAL
          ANG_L_7
          ANG_L_8-VAL
          ANG_L_8
))