(cl:in-package msg_generate-msg)
(cl:export '(BALL_X-VAL
          BALL_X
          BALL_Y-VAL
          BALL_Y
          BALL_SPEED_X-VAL
          BALL_SPEED_X
          BALL_SPEED_Y-VAL
          BALL_SPEED_Y
          ROBOT_X-VAL
          ROBOT_X
          ROBOT_Y-VAL
          ROBOT_Y
          OBSTACLE0_X-VAL
          OBSTACLE0_X
          OBSTACLE0_Y-VAL
          OBSTACLE0_Y
          OBSTACLE1_X-VAL
          OBSTACLE1_X
          OBSTACLE1_Y-VAL
          OBSTACLE1_Y
          OBSTACLE2_X-VAL
          OBSTACLE2_X
          OBSTACLE2_Y-VAL
          OBSTACLE2_Y
          OBSTACLE3_X-VAL
          OBSTACLE3_X
          OBSTACLE3_Y-VAL
          OBSTACLE3_Y
))