(cl:in-package msg_generate-msg)
(cl:export '(LINE_CAM_X-VAL
          LINE_CAM_X
          LINE_CAM_Y-VAL
          LINE_CAM_Y
          LINE_2D_X-VAL
          LINE_2D_X
          LINE_2D_Y-VAL
          LINE_2D_Y
          LINE_D-VAL
          LINE_D
          LINE_THETA-VAL
          LINE_THETA
          CROSS_CAM_X-VAL
          CROSS_CAM_X
          CROSS_CAM_Y-VAL
          CROSS_CAM_Y
          CROSS_2D_X-VAL
          CROSS_2D_X
          CROSS_2D_Y-VAL
          CROSS_2D_Y
          CROSS_D-VAL
          CROSS_D
          HURDLE_CAM_X-VAL
          HURDLE_CAM_X
          HURDLE_CAM_Y-VAL
          HURDLE_CAM_Y
          HURDLE_2D_X-VAL
          HURDLE_2D_X
          HURDLE_2D_Y-VAL
          HURDLE_2D_Y
          HURDLE_D-VAL
          HURDLE_D
          HURDLE_THETA-VAL
          HURDLE_THETA
          PAN-VAL
          PAN
          TILT-VAL
          TILT
          SCAN_MODE-VAL
          SCAN_MODE
))