; Auto-generated. Do not edit!


(cl:in-package msg_generate-msg)


;//! \htmlinclude obsnavi.msg.html

(cl:defclass <obsnavi> (roslisp-msg-protocol:ros-message)
  ((DISTANCE
    :reader DISTANCE
    :initarg :DISTANCE
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (POINT_VEC_X
    :reader POINT_VEC_X
    :initarg :POINT_VEC_X
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (POINT_VEC_Y
    :reader POINT_VEC_Y
    :initarg :POINT_VEC_Y
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass obsnavi (<obsnavi>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <obsnavi>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'obsnavi)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name msg_generate-msg:<obsnavi> is deprecated: use msg_generate-msg:obsnavi instead.")))

(cl:ensure-generic-function 'DISTANCE-val :lambda-list '(m))
(cl:defmethod DISTANCE-val ((m <obsnavi>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader msg_generate-msg:DISTANCE-val is deprecated.  Use msg_generate-msg:DISTANCE instead.")
  (DISTANCE m))

(cl:ensure-generic-function 'POINT_VEC_X-val :lambda-list '(m))
(cl:defmethod POINT_VEC_X-val ((m <obsnavi>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader msg_generate-msg:POINT_VEC_X-val is deprecated.  Use msg_generate-msg:POINT_VEC_X instead.")
  (POINT_VEC_X m))

(cl:ensure-generic-function 'POINT_VEC_Y-val :lambda-list '(m))
(cl:defmethod POINT_VEC_Y-val ((m <obsnavi>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader msg_generate-msg:POINT_VEC_Y-val is deprecated.  Use msg_generate-msg:POINT_VEC_Y instead.")
  (POINT_VEC_Y m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <obsnavi>) ostream)
  "Serializes a message object of type '<obsnavi>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'DISTANCE))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'DISTANCE))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'POINT_VEC_X))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'POINT_VEC_X))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'POINT_VEC_Y))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'POINT_VEC_Y))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <obsnavi>) istream)
  "Deserializes a message object of type '<obsnavi>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'DISTANCE) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'DISTANCE)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'POINT_VEC_X) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'POINT_VEC_X)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'POINT_VEC_Y) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'POINT_VEC_Y)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<obsnavi>)))
  "Returns string type for a message object of type '<obsnavi>"
  "msg_generate/obsnavi")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'obsnavi)))
  "Returns string type for a message object of type 'obsnavi"
  "msg_generate/obsnavi")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<obsnavi>)))
  "Returns md5sum for a message object of type '<obsnavi>"
  "91095f1ce1738209df71690fed654828")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'obsnavi)))
  "Returns md5sum for a message object of type 'obsnavi"
  "91095f1ce1738209df71690fed654828")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<obsnavi>)))
  "Returns full string definition for message of type '<obsnavi>"
  (cl:format cl:nil "float64[] DISTANCE~%float64[] POINT_VEC_X~%float64[] POINT_VEC_Y~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'obsnavi)))
  "Returns full string definition for message of type 'obsnavi"
  (cl:format cl:nil "float64[] DISTANCE~%float64[] POINT_VEC_X~%float64[] POINT_VEC_Y~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <obsnavi>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'DISTANCE) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'POINT_VEC_X) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'POINT_VEC_Y) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <obsnavi>))
  "Converts a ROS message object to a list"
  (cl:list 'obsnavi
    (cl:cons ':DISTANCE (DISTANCE msg))
    (cl:cons ':POINT_VEC_X (POINT_VEC_X msg))
    (cl:cons ':POINT_VEC_Y (POINT_VEC_Y msg))
))
